name: 爬取EPG信息

on:
  workflow_dispatch:    # 手动触发
  schedule:
    - cron: '0 * * * *' # 每小时自动爬一次

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 下载 XML
      - name: Download playback.xml
        run: |
          curl -sSL --retry 3 --connect-timeout 10 -o playback.xml "http://47.110.243.216:51234/playback.xml"
          cat playback.xml  # 打印内容方便日志查看

      # 只有文件变化才提交，不变就直接跳过
      - name: Commit & Push only if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playback.xml

          # 判断文件是否变化
          if git diff --cached --quiet; then
            echo "✅ 文件没有变化，跳过提交"
            exit 0
          fi

          git commit -m "Auto update playback.xml"
          git push
