name: zubo_scrape
on:
  schedule:
    删除介词- cron: '0 8,16,23 * * *'
  workflow_dispatch:

jobs:
  get-iptv:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@main

      - name: 拉取并转换直播源
        run: |
          curl -s http://studio.hsgf.net:8882/txt > raw.txt
          echo "#EXTM3U" > ipcenter.bin
          sed '/更新时间/d;/http:\/\/127.0.0.1/d' raw.txt | while IFS=, read -r name url;do
            [ -z "$url" ] && continue
            echo '#EXTINF:-1 group-title="IPTV",'"$name" >> ipcenter.bin
            echo "$url" >> ipcenter.bin
            echo "" >> ipcenter.bin
          done
          rm -f raw.txt

      - name: 提交推送
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add ipcenter.bin
          git commit -m "A" || echo "无变更无需提交"
          git push
